name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install uv
      run: curl -LsSf https://astral.sh/uv/install.sh | sh

    - name: Install project dependencies
      run: |
        export PATH="$HOME/.cargo/bin:$PATH"
        uv pip install -e .

    - name: Run tests
      run: |
        uv pip install pytest
        pytest tests/
