name: CI

permissions:
  contents: read

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH # Add uv to PATH for subsequent steps

    # --- FIX START ---
    # Add a step to create a virtual environment
    - name: Create Virtual Environment
      run: uv venv
    # --- FIX END ---

    - name: Install project dependencies
      run: |
        # uv commands automatically use the .venv created in the previous step
        uv pip install -e .

    - name: Run tests
      run: |
        # Install pytest into the virtual environment
        uv pip install pytest
        # Run pytest using uv run to ensure it uses the venv
        uv run pytest tests/

